### Module Importation and DataFrame Setup

In [1]:
# Reset the model for re-run
from tensorflow.keras import backend as K
K.clear_session()

# Import dependencies
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
import keras_tuner as kt
from tensorflow.keras.callbacks import EarlyStopping

In [2]:
# Read the preprocessed CSV file from the Dataset folder into a Pandas DataFrame (see logistic regression model for preprocessing)
dfSurvivals = pd.read_csv(
    Path("../CSV_OUTPUT/ML_Cleaned_DS_CSV.csv")
)

In [3]:
# Review the DataFrame
dfSurvivals.head()

,Passenger Id,Age,Sibling/Spouse Aboard,Parent/Children Aboard,Passenger Class,Fare,Embarkation Port,Survival Boat,Body Number,Survived,Female,Male
0,1,29.0000,0,0,1,211.3375,2,2,S,1,1,0
1,2,0.9167,1,2,1,151.5500,2,11,S,1,0,1
2,3,2.0000,1,2,1,151.5500,2,DNS,BNR,0,1,0
3,4,30.0000,1,2,1,151.5500,2,DNS,135,0,0,1
4,5,25.0000,1,2,1,151.5500,2,DNS,BNR,0,1,0

In [4]:
# Print DataFrame information to ensure no null values (data cleaned in previous notebook) and check datatypes
dfSurvivals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1308 entries, 0 to 1307
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Passenger Id            1308 non-null   int64
 1   Age                     1308 non-null   float64
 2   Sibling/Spouse Aboard   1308 non-null   int64
 3   Parent/Children Aboard  1308 non-null   int64
 4   Passenger Class         1308 non-null   int64
 5   Fare                    1308 non-null   float64
 6   Embarkation Port        1308 non-null   int64
 7   Survival Boat           1308 non-null   object
 8   Body Number             1308 non-null   object
 9   Survived                1308 non-null   int64
 10  Female                  1308 non-null   int64
 11  Male                    1308 non-null   int64
dtypes: float64(2), int64(8), object(2)
memory usage: 122.8+ KB

In [5]:
# Drop Passenger ID and Survival Boat columns
dfSurvivals = dfSurvivals.drop(['Passenger Id', 'Survival Boat'], axis=1)
dfSurvivals.head()

,Age,Sibling/Spouse Aboard,Parent/Children Aboard,Passenger Class,Fare,Embarkation Port,Body Number,Survived,Female,Male
0,29.0000,0,0,1,211.3375,2,S,1,1,0
1,0.9167,1,2,1,151.5500,2,S,1,0,1
2,2.0000,1,2,1,151.5500,2,BNR,0,1,0
3,30.0000,1,2,1,151.5500,2,135,0,0,1
4,25.0000,1,2,1,151.5500,2,BNR,0,1,0

In [6]:
# Encode Body Number column into three categories by defining custom function
# This function encodes whether the body was found: 0 is survived, 1 is body not recovered, and 2 is body found.

def encode_body(body_number):

    # Survivors
    if body_number == "S":
        return 0
    
    # Body not recovered
    elif body_number == "BNR":
        return 1
    
    # Body found
    else:
        return 2

# Call the encode_body function on the Body Number function
dfSurvivals["Body Number"] = dfSurvivals["Body Number"].apply(encode_body)

# Review DataFrame
dfSurvivals.head()

,Age,Sibling/Spouse Aboard,Parent/Children Aboard,Passenger Class,Fare,Embarkation Port,Body Number,Survived,Female,Male
0,29.0000,0,0,1,211.3375,2,0,1,1,0
1,0.9167,1,2,1,151.5500,2,0,1,0,1
2,2.0000,1,2,1,151.5500,2,1,0,1,0
3,30.0000,1,2,1,151.5500,2,2,0,0,1
4,25.0000,1,2,1,151.5500,2,1,0,1,0

### Split the data into X and y and then into testing and training sets

In [7]:
# Split the data into X (features) and y (target)

# Set the y variable, which is the target
y = dfSurvivals['Survived']

# Set the X variable, which includes all features escept the target
X = dfSurvivals.drop(columns=['Survived'])

In [8]:
# Split into testing and training sets using train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [9]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

### Compile, Train, and Evaluate the Model

In [10]:
# Get the number of input features
input_dim = X_train.shape[1]

# Function to create and compile the neural network
def create_model(hp):
    
    # Create a new model
    nn_model = tf.keras.models.Sequential()
    
    # Choose activation function for hidden layers
    activation = hp.Choice('activation',['relu','tanh','sigmoid'])
    
    # Add first hidden layer with hyperparameter-tuned settings
    nn_model.add(tf.keras.layers.Dense(units=hp.Int('first_units', 
        min_value=1, 
        max_value=10, 
        step=2), 
        activation=activation, 
        input_dim=input_dim))
    
    # Add second hidden layer with 10 neurons
    nn_model.add(tf.keras.layers.Dense(units=10, activation=activation))
    
    # Add output layer for binary classification
    nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))
    
    # Compile the model
    nn_model.compile(loss="binary_crossentropy", optimizer='adam', metrics=["accuracy", "Precision", "Recall"]) 
    
    # Return compiled model
    return nn_model

In [11]:
# Set up the kerastuner then allow it to search for best hyperparameters
tuner = kt.Hyperband(
    create_model,
    objective="val_accuracy",
    max_epochs=20,
    hyperband_iterations=2,
    overwrite=True)

# Perform hyperparameter search
tuner.search(X_train_scaled, y_train, epochs=20, validation_data=(X_test_scaled, y_test))

Trial 21 Complete [00h 00m 02s]
val_accuracy: 0.6269113421440125

Best val_accuracy So Far: 1.0
Total elapsed time: 00h 00m 44s
INFO:tensorflow:Oracle triggered exit

In [12]:
# Get the hyperparameters of the best model
best_hyper = tuner.get_best_hyperparameters(1)[0]
best_hyper.values

{'activation': 'tanh',
 'first_units': 9,
 'tuner/epochs': 20,
 'tuner/initial_epoch': 7,
 'tuner/bracket': 2,
 'tuner/round': 2,
 'tuner/trial_id': '0013'}

In [13]:
# Get the best model
best_model = tuner.get_best_models(1)[0]
best_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 9)                 90

 dense_1 (Dense)             (None, 10)                100

 dense_2 (Dense)             (None, 1)                 11

=================================================================
Total params: 201 (804.00 Byte)
Trainable params: 201 (804.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [14]:
# Train the model
fit_model = best_model.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
31/31 [==============================] - 1s 1ms/step - loss: 0.0353 - accuracy: 0.9990 - precision: 0.9974 - recall: 1.0000
Epoch 2/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0292 - accuracy: 0.9990 - precision: 0.9974 - recall: 1.0000
Epoch 3/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0246 - accuracy: 0.9990 - precision: 0.9974 - recall: 1.0000
Epoch 4/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0209 - accuracy: 0.9990 - precision: 0.9974 - recall: 1.0000
Epoch 5/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0180 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 6/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0156 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 7/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0137 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 8/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0121 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 9/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0107 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 10/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0096 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 11/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0087 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 12/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0078 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 13/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0071 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 14/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0065 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 15/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0059 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 16/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0055 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 17/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0051 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 18/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0047 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 19/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0044 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 20/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0041 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 21/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0038 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 22/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0036 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 23/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0034 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 24/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0032 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 25/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0030 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 26/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0028 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 27/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0027 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 28/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0025 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 29/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0024 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 30/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0023 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 31/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0022 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 32/100
31/31 [==============================] - 0s 3ms/step - loss: 0.0021 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 33/100
31/31 [==============================] - 0s 2ms/step - loss: 0.0020 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 34/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0019 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 35/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0018 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 36/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0018 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 37/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0017 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 38/100
31/31 [==============================] - 0s 2ms/step - loss: 0.0016 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 39/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0016 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 40/100
31/31 [==============================] - 0s 2ms/step - loss: 0.0015 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 41/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0014 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 42/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0014 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 43/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0013 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 44/100
31/31 [==============================] - 0s 2ms/step - loss: 0.0013 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 45/100
31/31 [==============================] - 0s 2ms/step - loss: 0.0012 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 46/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0012 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 47/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0012 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 48/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0011 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 49/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0011 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 50/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0010 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 51/100
31/31 [==============================] - 0s 1ms/step - loss: 0.0010 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 52/100
31/31 [==============================] - 0s 1ms/step - loss: 9.8225e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 53/100
31/31 [==============================] - 0s 1ms/step - loss: 9.5192e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 54/100
31/31 [==============================] - 0s 1ms/step - loss: 9.2239e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 55/100
31/31 [==============================] - 0s 1ms/step - loss: 8.9447e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 56/100
31/31 [==============================] - 0s 1ms/step - loss: 8.6769e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 57/100
31/31 [==============================] - 0s 1ms/step - loss: 8.4220e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 58/100
31/31 [==============================] - 0s 1ms/step - loss: 8.1744e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 59/100
31/31 [==============================] - 0s 1ms/step - loss: 7.9375e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 60/100
31/31 [==============================] - 0s 1ms/step - loss: 7.7141e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 61/100
31/31 [==============================] - 0s 1ms/step - loss: 7.4949e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 62/100
31/31 [==============================] - 0s 1ms/step - loss: 7.2871e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 63/100
31/31 [==============================] - 0s 1ms/step - loss: 7.0851e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 64/100
31/31 [==============================] - 0s 1ms/step - loss: 6.8929e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 65/100
31/31 [==============================] - 0s 1ms/step - loss: 6.7055e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 66/100
31/31 [==============================] - 0s 1ms/step - loss: 6.5275e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 67/100
31/31 [==============================] - 0s 1ms/step - loss: 6.3542e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 68/100
31/31 [==============================] - 0s 1ms/step - loss: 6.1876e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 69/100
31/31 [==============================] - 0s 1ms/step - loss: 6.0282e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 70/100
31/31 [==============================] - 0s 1ms/step - loss: 5.8717e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 71/100
31/31 [==============================] - 0s 1ms/step - loss: 5.7214e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 72/100
31/31 [==============================] - 0s 1ms/step - loss: 5.5765e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 73/100
31/31 [==============================] - 0s 1ms/step - loss: 5.4367e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 74/100
31/31 [==============================] - 0s 1ms/step - loss: 5.3016e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 75/100
31/31 [==============================] - 0s 1ms/step - loss: 5.1723e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 76/100
31/31 [==============================] - 0s 1ms/step - loss: 5.0445e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 77/100
31/31 [==============================] - 0s 1ms/step - loss: 4.9236e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 78/100
31/31 [==============================] - 0s 1ms/step - loss: 4.8042e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 79/100
31/31 [==============================] - 0s 1ms/step - loss: 4.6902e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 80/100
31/31 [==============================] - 0s 1ms/step - loss: 4.5786e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 81/100
31/31 [==============================] - 0s 1ms/step - loss: 4.4720e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 82/100
31/31 [==============================] - 0s 1ms/step - loss: 4.3676e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 83/100
31/31 [==============================] - 0s 1ms/step - loss: 4.2670e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 84/100
31/31 [==============================] - 0s 1ms/step - loss: 4.1686e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 85/100
31/31 [==============================] - 0s 1ms/step - loss: 4.0742e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 86/100
31/31 [==============================] - 0s 1ms/step - loss: 3.9818e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 87/100
31/31 [==============================] - 0s 1ms/step - loss: 3.8925e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 88/100
31/31 [==============================] - 0s 1ms/step - loss: 3.8056e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 89/100
31/31 [==============================] - 0s 1ms/step - loss: 3.7211e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 90/100
31/31 [==============================] - 0s 1ms/step - loss: 3.6389e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 91/100
31/31 [==============================] - 0s 1ms/step - loss: 3.5592e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 92/100
31/31 [==============================] - 0s 1ms/step - loss: 3.4827e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 93/100
31/31 [==============================] - 0s 1ms/step - loss: 3.4066e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 94/100
31/31 [==============================] - 0s 1ms/step - loss: 3.3339e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 95/100
31/31 [==============================] - 0s 1ms/step - loss: 3.2624e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 96/100
31/31 [==============================] - 0s 1ms/step - loss: 3.1932e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 97/100
31/31 [==============================] - 0s 1ms/step - loss: 3.1258e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 98/100
31/31 [==============================] - 0s 1ms/step - loss: 3.0601e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 99/100
31/31 [==============================] - 0s 1ms/step - loss: 2.9961e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 100/100
31/31 [==============================] - 0s 1ms/step - loss: 2.9337e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000

In [15]:
# Evaluate the model using the test data
model_loss, model_accuracy, model_precision, model_recall = best_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}, Precision: {model_precision}, Recall: {model_recall}")

11/11 - 0s - loss: 4.1911e-04 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000 - 237ms/epoch - 22ms/step
Loss: 0.00041911128209903836, Accuracy: 1.0, Precision: 1.0, Recall: 1.0

In [16]:
# Use the model to make predictions on test data
y_pred_prob = best_model.predict(X_test_scaled).flatten()
y_pred = [1 if prob >= 0.5 else 0 for prob in y_pred_prob]

# Generate a confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Generate a classification report
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

11/11 [==============================] - 0s 1ms/step
Confusion Matrix:
[[205   0]
 [  0 122]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       205
           1       1.00      1.00      1.00       122

    accuracy                           1.00       327
   macro avg       1.00      1.00      1.00       327
weighted avg       1.00      1.00      1.00       327

In [17]:
# Export our model to keras file
best_model.save('OUPUT/Titanic_survival_mod1.keras')